In [4]:

import numpy as np

d1 = 9  # Last digit of student ID
d2 = 1  # Second last digit of student ID

# matrix A  d1 and d2
A = np.array([
    [d1 + 2, d2 + 1],
    [2 * d1, d2 + 2]
])

# Print the matrix
print(A)


[[11  2]
 [18  3]]


In [5]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

d1 = 9
d2 = 1

A = np.array([[d1+2, d2+1], [2*d1, d2+2]])

#shape of A
print("shape of matrix A is: ", A.shape)

# determinant
det = np.linalg.det(A)
print("determinant of A: ", det)

# rank
rank = np.linalg.matrix_rank(A)
print("rank of matrix A is: ", rank)

# eigenvalues
eigvals = np.linalg.eigvals(A)
print("eigen values: ", eigvals)

# inverse of matrix A (if exists)
if abs(det) > 0.0001:
    inv = np.linalg.inv(A)
    print("inverse of matrix A is:\n", inv)
else:
    print("determinant is zero, inverse cannot be calculated")

shape of matrix A is:  (2, 2)
determinant of A:  -3.000000000000005
rank of matrix A is:  2
eigen values:  [14.21110255 -0.21110255]
inverse of matrix A is:
 [[-1.          0.66666667]
 [ 6.         -3.66666667]]


In [6]:
import numpy as np

d1 = 9
d2 = 1

# Step 1: Original matrix A
A = np.array([[d1+2, d2+1], [2*d1, d2+2]])
print("Original matrix A:\n", A)

# Step 2 (Question 3): Create matrix B by changing ONE element
B = A.copy()
B[0, 0] = B[0, 0] + 1  # Changed element: top-left (row 0, column 0) → added +1
print("\n[Q3] Changed element: A[0,0] (top-left) by adding +1")
print("New matrix B:\n", B)

# Step 3 (Question 4): Re-analyze matrix B
print("\n[Q4] Analysis of matrix B:")

print("shape of matrix B is: ", B.shape)
print("determinant of B: ", np.linalg.det(B))
print("rank of matrix B is: ", np.linalg.matrix_rank(B))
print("eigen values: ", np.linalg.eigvals(B))

det_B = np.linalg.det(B)
if abs(det_B) > 1e-10:
    print("inverse of matrix B is:\n", np.linalg.inv(B))
else:
    print("determinant is zero, inverse does not exist")

Original matrix A:
 [[11  2]
 [18  3]]

[Q3] Changed element: A[0,0] (top-left) by adding +1
New matrix B:
 [[12  2]
 [18  3]]

[Q4] Analysis of matrix B:
shape of matrix B is:  (2, 2)
determinant of B:  0.0
rank of matrix B is:  1
eigen values:  [15.  0.]
determinant is zero, inverse does not exist
