In [11]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# New Section

In [12]:
import numpy as np

# Updated scalar and array inputs
scalar = 3.7
arr = np.array([7, 5, 6, 9, 13, 17])  # 6 elements as required

# Trigonometric functions (input in radians)
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized to [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm (ln)

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by scalar (3.7)
rem_values = np.remainder(arr, scalar)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display all results
print("Array:", arr)
print("Scalar:", scalar)
print("\n Trigonometric Functions ")
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin (normalized):", asin_values)
print("acos (normalized):", acos_values)
print("atan:", atan_values)

print("\n Exponential & Logarithm ")
print("exp:", exp_values)
print("log (natural):", log_values)

print("\n Other Functions ")
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print(f"remainder (÷ {scalar}):", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

Array: [ 7  5  6  9 13 17]
Scalar: 3.7

 Trigonometric Functions 
sin: [ 0.6569866  -0.95892427 -0.2794155   0.41211849  0.42016704 -0.96139749]
cos: [ 0.75390225  0.28366219  0.96017029 -0.91113026  0.90744678 -0.27516334]
tan: [ 0.87144798 -3.38051501 -0.29100619 -0.45231566  0.46302113  3.49391565]
asin (normalized): [0.42438971 0.2985322  0.36071272 0.55790704 0.87058477 1.57079633]
acos (normalized): [1.14640662 1.27226413 1.21008361 1.01288929 0.70021156 0.        ]
atan: [1.42889927 1.37340077 1.40564765 1.46013911 1.49402444 1.5120405 ]

 Exponential & Logarithm 
exp: [1.09663316e+03 1.48413159e+02 4.03428793e+02 8.10308393e+03
 4.42413392e+05 2.41549528e+07]
log (natural): [1.94591015 1.60943791 1.79175947 2.19722458 2.56494936 2.83321334]

 Other Functions 
abs: [ 7  5  6  9 13 17]
sqrt: [2.64575131 2.23606798 2.44948974 3.         3.60555128 4.12310563]
remainder (÷ 3.7): [3.3 1.3 2.3 1.6 1.9 2.2]
round: [ 7  5  6  9 13 17]
floor: [ 7.  5.  6.  9. 13. 17.]
ceil: [ 7.  5.  6.

# New Section

In [13]:
import numpy as np

matrix = np.array([[9, -4], [-7, 5]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(np.abs(matrix)), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(np.abs(matrix)), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(np.abs(matrix))

abs_values = np.abs(matrix)
sqrt_values = np.sqrt(np.abs(matrix))

rem_values = np.remainder(matrix, 2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasin:\n", asin_values)
print("\nacos:\n", acos_values)
print("\natan:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog:\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem:\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[ 9 -4]
 [-7  5]]

sin:
 [[ 0.41211849  0.7568025 ]
 [-0.6569866  -0.95892427]]

cos:
 [[-0.91113026 -0.65364362]
 [ 0.75390225  0.28366219]]

tan:
 [[-0.45231566 -1.15782128]
 [-0.87144798 -3.38051501]]

asin:
 [[ 1.57079633 -0.46055399]
 [-0.89112251  0.58903097]]

acos:
 [[0.         2.03135032]
 [2.46191883 0.98176536]]

atan:
 [[ 1.46013911 -1.32581766]
 [-1.42889927  1.37340077]]

exp:
 [[8.10308393e+03 1.83156389e-02]
 [9.11881966e-04 1.48413159e+02]]

log:
 [[2.19722458 1.38629436]
 [1.94591015 1.60943791]]

abs:
 [[9 4]
 [7 5]]

sqrt:
 [[3.         2.        ]
 [2.64575131 2.23606798]]

rem:
 [[1 0]
 [1 1]]

round:
 [[ 9 -4]
 [-7  5]]

floor:
 [[ 9. -4.]
 [-7.  5.]]

ceil:
 [[ 9. -4.]
 [-7.  5.]]


# New Section

In [14]:
import numpy as np

matrix = np.array([[7, -3], [-8, 4], [11, -6]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(np.abs(matrix)), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(np.abs(matrix)), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(np.abs(matrix))

abs_values = np.abs(matrix)
sqrt_values = np.sqrt(np.abs(matrix))

rem_values = np.remainder(matrix, 2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasin:\n", asin_values)
print("\nacos:\n", acos_values)
print("\natan:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog:\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem:\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[ 7 -3]
 [-8  4]
 [11 -6]]

sin:
 [[ 0.6569866  -0.14112001]
 [-0.98935825 -0.7568025 ]
 [-0.99999021  0.2794155 ]]

cos:
 [[ 0.75390225 -0.9899925 ]
 [-0.14550003 -0.65364362]
 [ 0.0044257   0.96017029]]

tan:
 [[ 8.71447983e-01  1.42546543e-01]
 [ 6.79971146e+00  1.15782128e+00]
 [-2.25950846e+02  2.91006191e-01]]

asin:
 [[ 0.689775   -0.27622663]
 [-0.81433994  0.37216853]
 [ 1.57079633 -0.57693135]]

acos:
 [[0.88102133 1.84702296]
 [2.38513627 1.19862779]
 [0.         2.14772767]]

atan:
 [[ 1.42889927 -1.24904577]
 [-1.44644133  1.32581766]
 [ 1.48013644 -1.40564765]]

exp:
 [[1.09663316e+03 4.97870684e-02]
 [3.35462628e-04 5.45981500e+01]
 [5.98741417e+04 2.47875218e-03]]

log:
 [[1.94591015 1.09861229]
 [2.07944154 1.38629436]
 [2.39789527 1.79175947]]

abs:
 [[ 7  3]
 [ 8  4]
 [11  6]]

sqrt:
 [[2.64575131 1.73205081]
 [2.82842712 2.        ]
 [3.31662479 2.44948974]]

rem:
 [[1 1]
 [0 0]
 [1 0]]

round:
 [[ 7 -3]
 [-8  4]
 [11 -6]]

floor:
 [[ 7. -3.]
 [-8.  4.]
 [

# New Section

In [15]:
import numpy as np

matrix = np.array([[3.7, -1.2, 8.4], [0.5, 6.9, -4.3]])

max_val = np.max(matrix)
max_idx = np.unravel_index(np.argmax(matrix), matrix.shape)

min_val = np.min(matrix)
min_idx = np.unravel_index(np.argmin(matrix), matrix.shape)

length = matrix.size

sorted_rows = -np.sort(-matrix, axis=1)
sorted_all = -np.sort(-matrix.flatten())

total_sum = np.sum(matrix)
total_prod = np.prod(matrix)

median = np.median(matrix)
mean = np.mean(matrix)
std = np.std(matrix)

print("Matrix:\n", matrix)
print("\nMax:", max_val, "at position", max_idx)
print("Min:", min_val, "at position", min_idx)
print("Length (total elements):", length)
print("Row-wise sorted (descending):\n", sorted_rows)
print("Entire matrix sorted (descending):", sorted_all)
print("Sum:", total_sum)
print("Product:", total_prod)
print("Median:", median)
print("Mean:", mean)
print("Standard deviation:", std)

Matrix:
 [[ 3.7 -1.2  8.4]
 [ 0.5  6.9 -4.3]]

Max: 8.4 at position (np.int64(0), np.int64(2))
Min: -4.3 at position (np.int64(1), np.int64(2))
Length (total elements): 6
Row-wise sorted (descending):
 [[ 8.4  3.7 -1.2]
 [ 6.9  0.5 -4.3]]
Entire matrix sorted (descending): [ 8.4  6.9  3.7  0.5 -1.2 -4.3]
Sum: 14.0
Product: 553.2861600000001
Median: 2.1
Mean: 2.3333333333333335
Standard deviation: 4.460443425888905
